<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class UserManualSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = array(
            array('id' => '1','first_name' => 'Mohamed','middle_name' => NULL,'last_name' => 'Juma','salutation' => 'Mr.','username' => 'moh','email' => 'madyrio100@gmail.com','phone' => '658106643','deleted_at' => NULL,'email_verified_at' => '2022-01-21 16:04:40','password' => '$2y$10$Mbf3eQCbA0C5yzVhuFKtL.ikWENM0yAn408l9rsxOdMpA.Rw8XFTC','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => 'FSfmEMbsWs68UOaIsGBwfT3deyUyyCJevrWEq43EUy8vcdMTopAwmWisywa2','created_at' => '2022-01-21 16:04:41','updated_at' => '2022-10-27 15:22:12'),
            array('id' => '2','first_name' => 'Furaha','middle_name' => NULL,'last_name' => 'Mwangosi','salutation' => NULL,'username' => 'mwangosi','email' => 'mwangosi@gmail.com','phone' => NULL,'deleted_at' => NULL,'email_verified_at' => '2022-01-21 16:04:41','password' => '$2y$10$LmL9u8M354nckBSO7TOWR.Q/r1drdfEBt157Id7SbxaCon.NfqCJC','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => NULL,'created_at' => '2022-01-21 16:04:41','updated_at' => '2022-01-21 16:04:41'),
            array('id' => '3','first_name' => 'Michael','middle_name' => NULL,'last_name' => 'Fidelis','salutation' => NULL,'username' => 'mfidelis','email' => 'mfidelis@mustnet.ac.tz','phone' => '620874788','deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$ImrLhdRH6PM1S6Ry3E.jE.7M6NR6s3/JQElIrfROe9gj8u026dYFu','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => NULL,'created_at' => '2022-01-21 16:21:08','updated_at' => '2022-01-21 16:21:08'),
            array('id' => '4','first_name' => 'John','middle_name' => 'Nathan','last_name' => 'Mgimba','salutation' => NULL,'username' => 'jmgimba','email' => 'mgimba.john11@gmail.com','phone' => '763070324','deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$pet0aNlUxugOh4F2/wGr4e1flg4Aaq5zcF0mRZDXGQ/czczBPQbxC','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => NULL,'created_at' => '2022-01-24 09:15:11','updated_at' => '2022-05-12 13:12:39'),
            array('id' => '5','first_name' => 'David','middle_name' => 'Luje','last_name' => 'Lutatunda','salutation' => NULL,'username' => 'dlutatunda','email' => 'davidluje88@gmail.com','phone' => '752727042','deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$cxmKihBLcSV5cuO8vNJSVOEL9u.gxmBxe1DvBfi4RqkCgV9OqFJ.G','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => '2iFvkrixNZHmYOOJjqWyRwP10LjLd99u94MJcHitDUFZomxmWSGBhzJovQNo','created_at' => '2022-01-24 09:16:07','updated_at' => '2022-02-10 13:14:16'),
            array('id' => '6','first_name' => 'Huruma','middle_name' => NULL,'last_name' => 'Selemani','salutation' => NULL,'username' => 'hselemani','email' => 'hurumaselemani95@gmail.com','phone' => '765867736','deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$zy8NA/jZS41bpVj/bkVu7OAu1JiZmkVi27oORCyVNFNW42aRaGcy6','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => NULL,'created_at' => '2022-01-24 09:17:14','updated_at' => '2022-01-24 09:17:14'),
            array('id' => '7','first_name' => 'Martin','middle_name' => 'Peter','last_name' => 'Kimisha','salutation' => NULL,'username' => 'mkimisha','email' => 'martinkimisha44@gmail.com','phone' => '629429806','deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$rWXDj./55gGc2nBgxi.ngujDkSY6uis1kX6d1ABqyUGm2ykofUqxO','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => 'CgIgpz2SAV1nvUTqTbAj46zesUFbFcm0Lw9dvtpCcWeimly2DYhGJcI2c7nG','created_at' => '2022-01-25 09:16:55','updated_at' => '2022-09-27 19:39:20'),
            array('id' => '8','first_name' => 'Edwin','middle_name' => 'Edward','last_name' => 'Cyprian','salutation' => NULL,'username' => 'ecyprian','email' => 'cyprianedwin500@gmail.com','phone' => '752475308','deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$BmmPyrO1sHaHL1G3p5//VeYLdD6/fRoQw4Mqb8tQfKs6/d1kstVmW','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => NULL,'created_at' => '2022-01-31 11:59:38','updated_at' => '2022-02-10 13:12:52'),
            array('id' => '9','first_name' => 'Charles','middle_name' => 'Yohana','last_name' => 'Mkwiji','salutation' => NULL,'username' => 'cmkwiji','email' => 'gwattmale@gmail.com','phone' => '756533666','deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$ptxBoteQEW.opf9s9TmxdOzKsgazXRr/fk1aHnJFEPf9qqdZ6tMaC','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => '5n0fbtFRFfo3dfCGhMseRUWkod8J5XV9TLGMTEdetJtkazyKtZfbrFsJaU3D','created_at' => '2022-02-04 21:45:07','updated_at' => '2022-02-04 21:45:07'),
            array('id' => '10','first_name' => 'Mwamini','middle_name' => 'Onesty','last_name' => 'Salingo','salutation' => NULL,'username' => 'msalingo','email' => 'salingomwamini261@gmail.com','phone' => '623536000','deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$f3jV8XC2xG5oE0wLf9dAx.L3PlLuEjkvImeIvVb9uqZWphGhhrd5i','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => 'w08PwyqnCs68lyKjCo5sYvkk3QDlqCEZbdn4fLFlDG27lEbNbiQsS6J5tBHQ','created_at' => '2022-02-04 21:46:37','updated_at' => '2022-02-15 10:29:48'),
            array('id' => '11','first_name' => 'Naftali','middle_name' => 'Amani','last_name' => 'Mshana','salutation' => 'Mr.','username' => 'nmshana','email' => 'amanynaftaly360@gmail.com','phone' => '652474499','deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$OJ5Xl1phLehCVuAEmbXrgeB2pNJu3yyoe4/4P5X8C3THvqPNEqEDi','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => 'YHfBdndBibxR9anAHaEfG5KdfYqnEx445vzYotzoTlcMvcikD3yFTWvXQF25','created_at' => '2022-02-15 10:23:57','updated_at' => '2022-11-16 12:22:32'),
            array('id' => '12','first_name' => 'Rashid','middle_name' => 'M','last_name' => 'Mponda','salutation' => NULL,'username' => 'rmponda','email' => 'rashid@test.com','phone' => NULL,'deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$JRRxQ5w/5APCr/4XeA0DsOs6sgMb0riCuyXt36nMOCUA3SWDLxmMm','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => 'q1yYRNSuhHMsTaX22CBNRuFHaZcOcUo6Pc2LS8cwq63LK6XLhAnBXD6TsjQO','created_at' => '2022-04-27 14:54:54','updated_at' => '2022-04-27 14:54:54'),
            array('id' => '13','first_name' => 'Grace','middle_name' => 'Bisendile','last_name' => 'Mwasonya','salutation' => NULL,'username' => 'gmwasonya','email' => 'bisendilegrace@gmail.com','phone' => '756347910','deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$NOhjCPWvieTEgQW8qZoKL.HpUzoGwDK3VlhveWfpknbkyQYJh9Nmy','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => NULL,'created_at' => '2022-06-09 10:35:06','updated_at' => '2022-06-09 10:35:06'),
            array('id' => '14','first_name' => 'Diana','middle_name' => NULL,'last_name' => 'Luambano','salutation' => NULL,'username' => 'dluambano','email' => 'dluambano14@gmail.com','phone' => '765709705','deleted_at' => NULL,'email_verified_at' => NULL,'password' => '$2y$10$MlfjRyVfBIa1L/VIv5/F/OOOkmbsmiAwFipcK1f.Uegthod4gWN22','two_factor_secret' => NULL,'two_factor_recovery_codes' => NULL,'remember_token' => NULL,'created_at' => '2022-10-12 17:48:43','updated_at' => '2022-10-12 17:48:43')
          );

          foreach ($users as $user) {
            $user = collect($user)->merge(['station_id' => 2]);
                User::firstOrCreate($user->only('username')->toArray(), $user->except('username','id')->toArray());
          }
    }
}
